version: 2.1

jobs:
  install-and-test-backend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Run Backend build
          command: |
            cd backend
            npm run build

  install-and-test-frontend:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Run Frontend build
          command: |
            cd frontend
            npm run build

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - install-and-test-backend
      - install-and-test-frontend
